application: knowmyoffers
version: uat
runtime: python27
threadsafe: true
api_version: 1

handlers:
- url: /Sitemap.xml
  static_files: Sitemap.xml
  upload: Sitemap.xml

- url: /static
  static_dir: static

- url: /admin
  script: admin.app
  
- url: /offer
  script: offersnstores.app
  
- url: /store
  script: offersnstores.app
  
- url: /.*
  script: main.app
  
libraries:
- name: webapp2
  version: latest